version: '3.9'

services:
  arc-backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - '../prod:/app'
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ../db:/data/db:delegated
