version: '3.9'

services:
  arc-backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - mongodb
    volumes:
      - '../:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - ../db:/data/db:delegated
